view:
  increase_index: 1
  width_image: 50
  height_image: 50
  device:
    information_length: 100
    per_page: 10
  borrow_device:
    per_page: 10
  user:
    default_avatar: "default-avatar.jpg"
  devise:
    off_auto: "off"
server:
  min_size: 0
  export_format: "xls"
